timeout: 1 # better for trying on real hardware

kaslr: yes
verbose: yes

#wallpaper: boot():/boot/bg.jpg
default_entry: 0

#term_font: boot():/boot/liminefont.f15
#term_font_size: 8x15
#term_font_spacing: 0

# ----
# Dualslot kernel system
# ----

# entry0 default/ active
/try emexOS
    protocol: limine
    cmdline: try

    kernel_path: boot():/boot/kernel_a.elf
    module_path: boot():/boot/initrd.cpio
    module_path: boot():/boot/initrdh.cpio
    module_path: boot():/EFI/BOOT/BOOTX64.EFI

# entry2
/install emexOS
    cmdline: install
    protocol: limine
    # the slot is A because the kernel A installs kernel B which isn't used
    kernel_path: boot():/boot/kernel_a.elf
    module_path: boot():/boot/initrd.cpio
    module_path: boot():/boot/initrdh.cpio
    module_path: boot():/boot/kernel_a.elf
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_path: boot():/boot/limine/limine-bios.sys

# slot 2 for update
# entry3
/emexOS B
    protocol: limine
    cmdline: try
    cmdline: slot_b

    kernel_path: boot():/boot/kernel_b.elf
    module_path: boot():/boot/initrd.cpio
    module_path: boot():/boot/initrdh.cpio
    module_path: boot():/EFI/BOOT/BOOTX64.EFI


# ----
# resolutions
# ----

#   resolution: 1920x1080x32
#   resolution: 2560x1440x32
#   resolution: 3840x2160x32
